// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPkvAZJDWaZvXq1BaIQ855m2XZT9zuAbo',
    appId: '1:999232748999:web:726a7d0e0af0ad811b2de2',
    messagingSenderId: '999232748999',
    projectId: 'sabgrocerynew',
    authDomain: 'sabgrocerynew.firebaseapp.com',
    databaseURL: 'https://sabgrocerynew-default-rtdb.firebaseio.com',
    storageBucket: 'sabgrocerynew.firebasestorage.app',
    measurementId: 'G-4D2XQCT4GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADTZmf3orJC8sFmURQIuVhLxGPRxYygtU',
    appId: '1:999232748999:android:bf9aa6e89712125e1b2de2',
    messagingSenderId: '999232748999',
    projectId: 'sabgrocerynew',
    databaseURL: 'https://sabgrocerynew-default-rtdb.firebaseio.com',
    storageBucket: 'sabgrocerynew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkCWtusQHprGNbj5GAiQR95E3_UHyaNEo',
    appId: '1:999232748999:ios:51a9cff8e29224ea1b2de2',
    messagingSenderId: '999232748999',
    projectId: 'sabgrocerynew',
    databaseURL: 'https://sabgrocerynew-default-rtdb.firebaseio.com',
    storageBucket: 'sabgrocerynew.firebasestorage.app',
    androidClientId: '999232748999-6dekhoae09k00e7lei64qrk5ec06gpch.apps.googleusercontent.com',
    iosClientId: '999232748999-rkt1s89hd3c105vhj2ugqhc7ar787tg2.apps.googleusercontent.com',
    iosBundleId: 'com.sabgrocery.userapp',
  );
}
